import { loadConfig } from "../utils/config";
import pc from "picocolors";
import path from "path";
import fs from "fs";
import storyblokToTypescript from "storyblok-generate-ts";

export async function generateTypes() {
  try {
    const config = await loadConfig();

    if (!config?.spaceId) {
      console.error(
        pc.red(
          "✗ No Storyblok Space ID found. Please run 'sb-migrate config' first."
        )
      );
      process.exit(1);
    }

    const schemaFile = path.join(
      process.cwd(),
      `components.${config.spaceId}.json`
    );
    const outputDir = path.join(process.cwd(), "storyblok", "types");
    const outputFile = path.join(outputDir, "storyblok.gen.d.ts");

    if (!fs.existsSync(schemaFile)) {
      console.error(
        pc.red(
          `✗ Components schema file not found at ${schemaFile}. Please run 'sb-migrate pull-components' first.`
        )
      );
      process.exit(1);
    }

    // Ensure output directory exists
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    console.log(pc.blue("Generating TypeScript types..."));

    try {
      await storyblokToTypescript({
        componentsJson: require(schemaFile),
        path: outputFile,
        titlePrefix: "Sb",
        titleSuffix: "",
        compilerOptions: {
          unknownAny: false,
          additionalProperties: false,
          bannerComment: `
            /**
             * This type/interface was automatically generated by sb-migrate generate-types.
             * DO NOT MODIFY IT BY HAND. Instead, run sb-migrate pull-components,
             * and then sb-migrate generate-types to regenerate this file.
            */`.trim(),
          unreachableDefinitions: true,
        },
        customTypeParser(key: string, obj: any) {
          const fieldType = obj.field_type;
          switch (fieldType) {
            case "storyblok-colorpicker":
            case "native-color-picker":
              return {
                [key]: {
                  type: "object",
                  properties: {
                    _uid: { type: "string" },
                    color: { type: "string" },
                    plugin: { type: "string" },
                  },
                },
              };
            case "seo-metatags":
              return {
                [key]: {
                  type: "object",
                  properties: {
                    _uid: { type: "string" },
                    title: { type: "string" },
                    plugin: { type: "string" },
                    og_image: { type: "string" },
                    og_title: { type: "string" },
                    description: { type: "string" },
                    twitter_image: { type: "string" },
                    twitter_title: { type: "string" },
                    og_description: { type: "string" },
                    twitter_description: { type: "string" },
                  },
                },
              };
            default:
              return {};
          }
        },
      });

      const fileContent = fs.readFileSync(outputFile, { encoding: "utf8" });

      // Add SbBlokData extension
      const content = fileContent.replace(
        /(export\s+interface\s+\w+)\s+(\{\n(?:\s+.*\n)*\})/g,
        (match, start, end) => {
          if (!end.includes("component:") || !end.includes("_uid:")) {
            return match;
          }
          return `${start} extends SbBlokData ${end}`;
        }
      );

      fs.writeFileSync(
        outputFile,
        `/* eslint-disable */\nimport type { SbBlokData } from '@storyblok/vue'\n${content}`,
        { encoding: "utf8" }
      );

      console.log(pc.green("✓ Successfully generated TypeScript types"));
    } catch (error) {
      console.error(pc.red("✗ Failed to generate TypeScript types"));
      process.exit(1);
    }
  } catch (error) {
    console.error(pc.red(`✗ Failed to generate types: ${error}`));
    process.exit(1);
  }
}
