name: PR Template Check

on:
  pull_request:
    types: [opened]

jobs:
  check-template:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Template
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const templateContent = await github.rest.repos.getContent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: '.github/pull_request_template.md'
            });

            const template = Buffer.from(templateContent.data.content, 'base64').toString();

            // Extract section headers from template
            const templateSections = template.split('####')
              .map(section => section.trim())
              .filter(section => section.length > 0)
              .map(section => {
                const lines = section.split('\n');
                return lines[0].trim();
              });

            // Extract section headers from PR body
            const prSections = pr.body.split('####')
              .map(section => section.trim())
              .filter(section => section.length > 0)
              .map(section => {
                const lines = section.split('\n');
                return lines[0].trim();
              });

            // Check if all required sections are present
            const missingSections = templateSections.filter(section =>
              !prSections.some(prSection => prSection.includes(section))
            );

            if (missingSections.length > 0) {
              core.setFailed(`Please include all required sections in your PR description. Missing sections: ${missingSections.join(', ')}`);
            }
