name: PR Template Check

on:
  pull_request:
    types: [opened]

jobs:
  check-template:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Template
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const templateContent = await github.rest.repos.getContent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: '.github/pull_request_template.md'
            });

            const template = Buffer.from(templateContent.data.content, 'base64').toString();
            const templateSections = template.split('####').map(section => section.trim());

            // Check if PR body contains the template structure
            const hasTemplateStructure = templateSections.every(section => {
              if (!section) return true; // Skip empty sections
              return pr.body.includes(section);
            });

            if (!hasTemplateStructure) {
              core.setFailed('Please use the PR template when creating a pull request. You can find it in the PR description field.');
            }
