name: PR Validation

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate PR Title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            Feature
            Fix
            Docs
            Style
            Refactor
            Test
            Chore
          requireScope: false

      - name: Check PR Description
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const requiredSections = [
              'Description',
              'Changes Made',
              'How to Test'
            ];

            const missingSections = requiredSections.filter(section =>
              !pr.body.includes(`#### ${section}`)
            );

            if (missingSections.length > 0) {
              core.setFailed(`PR description is missing required sections: ${missingSections.join(', ')}`);
            }
